### ISSUE TITLE
If content too short, responsive is acting weirdly

### ISSUE THREAD

**Issue by Pipoupi** [lohanitech/ion-timeline#1]
Hello, 
Thanks for your really nice timeline. I'm facing an issue of CSS with short content, do you have any idea on how to fix that?

Here's an example : 
![image](https://user-images.githubusercontent.com/6475852/32062628-50cc4034-ba75-11e7-9708-5d3e54be3e1f.png)

**Comment by a-faraz** [comment]
@Pipoupi did you find a fix for this?

**Comment by Pipoupi** [comment]
@a-faraz I don't remember, and can't find where I used it. Sorry !

**Comment by a-faraz** [comment]
@Pipoupi it's okay, I figured it out. 

Had to change timeline-item from inline-block to block.

Thanks though!
